//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contoso.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ContosoRetailDWEntities : DbContext
    {
        public ContosoRetailDWEntities()
            : base("name=ContosoRetailDWEntities")
        {
            this.Configuration.ProxyCreationEnabled = false;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DimAccount> DimAccounts { get; set; }
        public virtual DbSet<DimChannel> DimChannels { get; set; }
        public virtual DbSet<DimCurrency> DimCurrencies { get; set; }
        public virtual DbSet<DimCustomer> DimCustomers { get; set; }
        public virtual DbSet<DimDate> DimDates { get; set; }
        public virtual DbSet<DimEmployee> DimEmployees { get; set; }
        public virtual DbSet<DimEntity> DimEntities { get; set; }
        public virtual DbSet<DimGeography> DimGeographies { get; set; }
        public virtual DbSet<DimMachine> DimMachines { get; set; }
        public virtual DbSet<DimOutage> DimOutages { get; set; }
        public virtual DbSet<DimProduct> DimProducts { get; set; }
        public virtual DbSet<DimProductCategory> DimProductCategories { get; set; }
        public virtual DbSet<DimProductSubcategory> DimProductSubcategories { get; set; }
        public virtual DbSet<DimPromotion> DimPromotions { get; set; }
        public virtual DbSet<DimSalesTerritory> DimSalesTerritories { get; set; }
        public virtual DbSet<DimScenario> DimScenarios { get; set; }
        public virtual DbSet<DimStore> DimStores { get; set; }
        public virtual DbSet<FactExchangeRate> FactExchangeRates { get; set; }
        public virtual DbSet<FactInventory> FactInventories { get; set; }
        public virtual DbSet<FactITMachine> FactITMachines { get; set; }
        public virtual DbSet<FactITSLA> FactITSLAs { get; set; }
        public virtual DbSet<FactOnlineSale> FactOnlineSales { get; set; }
        public virtual DbSet<FactSale> FactSales { get; set; }
        public virtual DbSet<FactSalesQuota> FactSalesQuotas { get; set; }
        public virtual DbSet<FactStrategyPlan> FactStrategyPlans { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
