//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contoso.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimMachine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DimMachine()
        {
            this.FactITMachines = new HashSet<FactITMachine>();
            this.FactITSLAs = new HashSet<FactITSLA>();
        }
    
        public int MachineKey { get; set; }
        public string MachineLabel { get; set; }
        public int StoreKey { get; set; }
        public string MachineType { get; set; }
        public string MachineName { get; set; }
        public string MachineDescription { get; set; }
        public string VendorName { get; set; }
        public string MachineOS { get; set; }
        public string MachineSource { get; set; }
        public string MachineHardware { get; set; }
        public string MachineSoftware { get; set; }
        public string Status { get; set; }
        public System.DateTime ServiceStartDate { get; set; }
        public Nullable<System.DateTime> DecommissionDate { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> ETLLoadID { get; set; }
        public Nullable<System.DateTime> LoadDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual DimStore DimStore { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactITMachine> FactITMachines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactITSLA> FactITSLAs { get; set; }
    }
}
