//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contoso.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimOutage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DimOutage()
        {
            this.FactITSLAs = new HashSet<FactITSLA>();
        }
    
        public int OutageKey { get; set; }
        public string OutageLabel { get; set; }
        public string OutageName { get; set; }
        public string OutageDescription { get; set; }
        public string OutageType { get; set; }
        public string OutageTypeDescription { get; set; }
        public string OutageSubType { get; set; }
        public string OutageSubTypeDescription { get; set; }
        public Nullable<int> ETLLoadID { get; set; }
        public Nullable<System.DateTime> LoadDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactITSLA> FactITSLAs { get; set; }
    }
}
