//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contoso.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimProductSubcategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DimProductSubcategory()
        {
            this.DimProducts = new HashSet<DimProduct>();
        }
    
        public int ProductSubcategoryKey { get; set; }
        public string ProductSubcategoryLabel { get; set; }
        public string ProductSubcategoryName { get; set; }
        public string ProductSubcategoryDescription { get; set; }
        public Nullable<int> ProductCategoryKey { get; set; }
        public Nullable<int> ETLLoadID { get; set; }
        public Nullable<System.DateTime> LoadDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimProduct> DimProducts { get; set; }
        public virtual DimProductCategory DimProductCategory { get; set; }
    }
}
