//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contoso.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactSalesQuota
    {
        public int SalesQuotaKey { get; set; }
        public int ChannelKey { get; set; }
        public int StoreKey { get; set; }
        public int ProductKey { get; set; }
        public System.DateTime DateKey { get; set; }
        public int CurrencyKey { get; set; }
        public int ScenarioKey { get; set; }
        public decimal SalesQuantityQuota { get; set; }
        public decimal SalesAmountQuota { get; set; }
        public decimal GrossMarginQuota { get; set; }
        public Nullable<int> ETLLoadID { get; set; }
        public Nullable<System.DateTime> LoadDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual DimChannel DimChannel { get; set; }
        public virtual DimCurrency DimCurrency { get; set; }
        public virtual DimDate DimDate { get; set; }
        public virtual DimProduct DimProduct { get; set; }
        public virtual DimScenario DimScenario { get; set; }
        public virtual DimStore DimStore { get; set; }
    }
}
