//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contoso.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactITMachine
    {
        public int ITMachinekey { get; set; }
        public int MachineKey { get; set; }
        public System.DateTime Datekey { get; set; }
        public Nullable<decimal> CostAmount { get; set; }
        public string CostType { get; set; }
        public Nullable<int> ETLLoadID { get; set; }
        public Nullable<System.DateTime> LoadDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual DimDate DimDate { get; set; }
        public virtual DimMachine DimMachine { get; set; }
    }
}
