//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contoso.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactStrategyPlan
    {
        public int StrategyPlanKey { get; set; }
        public System.DateTime Datekey { get; set; }
        public int EntityKey { get; set; }
        public int ScenarioKey { get; set; }
        public int AccountKey { get; set; }
        public int CurrencyKey { get; set; }
        public Nullable<int> ProductCategoryKey { get; set; }
        public decimal Amount { get; set; }
        public Nullable<int> ETLLoadID { get; set; }
        public Nullable<System.DateTime> LoadDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual DimAccount DimAccount { get; set; }
        public virtual DimCurrency DimCurrency { get; set; }
        public virtual DimDate DimDate { get; set; }
        public virtual DimEntity DimEntity { get; set; }
        public virtual DimProductCategory DimProductCategory { get; set; }
        public virtual DimScenario DimScenario { get; set; }
    }
}
