//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contoso.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactITSLA
    {
        public int ITSLAkey { get; set; }
        public System.DateTime DateKey { get; set; }
        public int StoreKey { get; set; }
        public int MachineKey { get; set; }
        public int OutageKey { get; set; }
        public System.DateTime OutageStartTime { get; set; }
        public System.DateTime OutageEndTime { get; set; }
        public int DownTime { get; set; }
        public Nullable<int> ETLLoadID { get; set; }
        public Nullable<System.DateTime> LoadDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual DimDate DimDate { get; set; }
        public virtual DimMachine DimMachine { get; set; }
        public virtual DimOutage DimOutage { get; set; }
        public virtual DimStore DimStore { get; set; }
    }
}
